"""Intent classification via multilingual sentence embeddings + cosine similarity."""
from __future__ import annotations
import functools

INTENTS = ["loan_request", "balance_check", "kyc_help", "complaint", "greeting", "general"]
THRESHOLD = 0.4

SEEDS: list[tuple[str, str]] = [
    # --- loan_request (en) ---
    ("loan_request", "I need a loan"),
    ("loan_request", "How do I apply for a personal loan?"),
    ("loan_request", "Tell me about home loan interest rates"),
    ("loan_request", "Can I get a car loan from this bank?"),
    ("loan_request", "What is the eligibility for a personal loan?"),
    ("loan_request", "I want to apply for a business loan"),
    ("loan_request", "How much loan can I get based on my salary?"),
    ("loan_request", "What documents are needed for a home loan?"),
    ("loan_request", "Is there a loan for education?"),
    ("loan_request", "I want to take a loan against my property"),
    ("loan_request", "What is the interest rate for personal loans?"),
    ("loan_request", "Can you help me apply for a loan?"),
    ("loan_request", "I need money urgently, do you offer loans?"),
    ("loan_request", "What is the EMI for a 5 lakh loan?"),
    ("loan_request", "How can I check my loan eligibility?"),
    ("loan_request", "I want a top-up on my existing loan"),
    # --- loan_request (hi) ---
    ("loan_request", "मुझे लोन चाहिए"),
    ("loan_request", "पर्सनल लोन कैसे लें?"),
    ("loan_request", "होम लोन की जानकारी दीजिए"),
    ("loan_request", "मुझे कार लोन लेना है"),
    ("loan_request", "लोन के लिए क्या दस्तावेज चाहिए?"),
    ("loan_request", "क्या मुझे एजुकेशन लोन मिल सकता है?"),
    ("loan_request", "मेरी सैलरी पर कितना लोन मिलेगा?"),
    ("loan_request", "लोन की ब्याज दर क्या है?"),
    ("loan_request", "बिजनेस लोन कैसे अप्लाई करें?"),
    ("loan_request", "मुझे तुरंत पैसों की जरूरत है, लोन मिल सकता है क्या?"),
    ("loan_request", "लोन अप्रूवल में कितना समय लगता है?"),
    ("loan_request", "personal loan kaise le sakta hoon"),
    ("loan_request", "mujhe ghar ke liye loan chahiye"),
    ("loan_request", "loan ki EMI kitni hogi"),
    ("loan_request", "क्या मेरा पुराना लोन टॉप-अप हो सकता है?"),
    ("loan_request", "गोल्ड लोन के बारे में बताइए"),
    # --- loan_request (gu) ---
    ("loan_request", "મારે લોન જોઈએ છે"),
    ("loan_request", "પર્સનલ લોન કેવી રીતે લેવી?"),
    ("loan_request", "હોમ લોન વિશે માહિતી આપો"),
    ("loan_request", "મારે કાર લોન લેવી છે"),
    ("loan_request", "લોન માટે કયા દસ્તાવેજ જોઈએ?"),
    ("loan_request", "એજ્યુકેશન લોન મળી શકે?"),
    ("loan_request", "મારા પગાર પર કેટલી લોન મળશે?"),
    ("loan_request", "લોનનો વ્યાજ દર કેટલો છે?"),
    ("loan_request", "બિઝનેસ લોન કેવી રીતે અરજી કરવી?"),
    ("loan_request", "મને તાત્કાલિક પૈસાની જરૂર છે, લોન મળી શકે?"),
    ("loan_request", "લોન મંજૂર થવામાં કેટલો સમય લાગે છે?"),
    ("loan_request", "ઘર માટે લોન જોઈએ છે"),
    ("loan_request", "ગોલ્ડ લોન વિશે જણાવો"),
    ("loan_request", "લોન ટોપ-અપ કેવી રીતે કરવું?"),
    ("loan_request", "મારે પ્રોપર્ટી પર લોન લેવી છે"),
    ("loan_request", "લોન એપ્લિકેશન સ્ટેટસ કેવી રીતે ચેક કરવું?"),

    # --- balance_check (en) ---
    ("balance_check", "What's my balance"),
    ("balance_check", "Check my account balance"),
    ("balance_check", "How much money do I have in my account?"),
    ("balance_check", "Show me my current balance"),
    ("balance_check", "I want to know my available balance"),
    ("balance_check", "Can you tell me my bank balance?"),
    ("balance_check", "What is the balance in my savings account?"),
    ("balance_check", "Please check my balance"),
    ("balance_check", "How much balance is left in my account?"),
    ("balance_check", "Balance enquiry"),
    ("balance_check", "I need to see my account statement balance"),
    ("balance_check", "What's the balance on my card?"),
    ("balance_check", "Tell me my current account balance"),
    ("balance_check", "Is there enough balance for this transaction?"),
    ("balance_check", "Check balance please"),
    ("balance_check", "How much do I have left in my wallet?"),
    # --- balance_check (hi) ---
    ("balance_check", "मेरा बैलेंस बताओ"),
    ("balance_check", "मेरे खाते में कितना पैसा है?"),
    ("balance_check", "अकाउंट बैलेंस चेक करो"),
    ("balance_check", "मेरा करंट बैलेंस क्या है?"),
    ("balance_check", "बैलेंस इंक्वायरी करनी है"),
    ("balance_check", "सेविंग अकाउंट में कितना बैलेंस है?"),
    ("balance_check", "मेरे खाते का बैलेंस दिखाओ"),
    ("balance_check", "kitna balance hai mere account mein"),
    ("balance_check", "मुझे अपना बैलेंस जानना है"),
    ("balance_check", "बैंक बैलेंस चेक करना है"),
    ("balance_check", "क्या मेरे अकाउंट में पैसे हैं?"),
    ("balance_check", "mera balance kitna hai"),
    ("balance_check", "मेरे कार्ड में कितना बैलेंस बचा है?"),
    ("balance_check", "अभी मेरे खाते में कितना बैलेंस है?"),
    ("balance_check", "बैलेंस की जानकारी दो"),
    ("balance_check", "मेरा वॉलेट बैलेंस कितना है?"),
    # --- balance_check (gu) ---
    ("balance_check", "મારો બેલેન્સ કેટલો છે"),
    ("balance_check", "મારા ખાતામાં કેટલા પૈસા છે?"),
    ("balance_check", "એકાઉન્ટ બેલેન્સ ચેક કરો"),
    ("balance_check", "મારું કરંટ બેલેન્સ શું છે?"),
    ("balance_check", "બેલેન્સ ઇન્ક્વાયરી કરવી છે"),
    ("balance_check", "સેવિંગ એકાઉન્ટમાં કેટલું બેલેન્સ છે?"),
    ("balance_check", "મારા ખાતાનું બેલેન્સ બતાવો"),
    ("balance_check", "મારે મારો બેલેન્સ જાણવો છે"),
    ("balance_check", "બેંક બેલેન્સ ચેક કરવો છે"),
    ("balance_check", "શું મારા ખાતામાં પૈસા છે?"),
    ("balance_check", "મારા કાર્ડમાં કેટલું બેલેન્સ બાકી છે?"),
    ("balance_check", "અત્યારે મારા ખાતામાં કેટલું બેલેન્સ છે?"),
    ("balance_check", "બેલેન્સની માહિતી આપો"),
    ("balance_check", "મારું વોલેટ બેલેન્સ કેટલું છે?"),
    ("balance_check", "મારે બેલેન્સ જોવો છે"),
    ("balance_check", "ખાતાની બેલેન્સ વિગત આપો"),

    # --- kyc_help (en) ---
    ("kyc_help", "Help with KYC"),
    ("kyc_help", "How to complete KYC"),
    ("kyc_help", "I need to update my KYC details"),
    ("kyc_help", "What documents are required for KYC?"),
    ("kyc_help", "My KYC is pending, what do I do?"),
    ("kyc_help", "How do I verify my identity for KYC?"),
    ("kyc_help", "KYC verification process"),
    ("kyc_help", "Is my KYC completed?"),
    ("kyc_help", "I want to submit my KYC documents online"),
    ("kyc_help", "Why is my KYC rejected?"),
    ("kyc_help", "How long does KYC verification take?"),
    ("kyc_help", "Can I do KYC through video call?"),
    ("kyc_help", "I need to re-KYC my account"),
    ("kyc_help", "What is KYC and why is it needed?"),
    ("kyc_help", "My account is on hold due to KYC"),
    ("kyc_help", "Steps to complete KYC online"),
    # --- kyc_help (hi) ---
    ("kyc_help", "KYC कैसे करें"),
    ("kyc_help", "मेरा KYC कैसे पूरा होगा?"),
    ("kyc_help", "KYC के लिए कौन से दस्तावेज चाहिए?"),
    ("kyc_help", "मेरा KYC पेंडिंग है, क्या करूं?"),
    ("kyc_help", "KYC वेरिफिकेशन कैसे होता है?"),
    ("kyc_help", "क्या मेरा KYC पूरा हो गया है?"),
    ("kyc_help", "मुझे अपने KYC दस्तावेज जमा करना है"),
    ("kyc_help", "मेरा KYC रिजेक्ट क्यों हुआ?"),
    ("kyc_help", "KYC वेरिफिकेशन में कितना समय लगता है?"),
    ("kyc_help", "क्या मैं वीडियो कॉल से KYC कर सकता हूं?"),
    ("kyc_help", "मुझे अपना अकाउंट फिर से KYC करना है"),
    ("kyc_help", "KYC kaise complete kare"),
    ("kyc_help", "mera KYC update karna hai"),
    ("kyc_help", "KYC नहीं होने से मेरा अकाउंट बंद हो गया है"),
    ("kyc_help", "ऑनलाइन KYC कैसे करें?"),
    ("kyc_help", "KYC के बिना अकाउंट काम नहीं कर रहा"),
    # --- kyc_help (gu) ---
    ("kyc_help", "KYC કેવી રીતે કરવું"),
    ("kyc_help", "મારું KYC કેવી રીતે પૂરું થશે?"),
    ("kyc_help", "KYC માટે કયા દસ્તાવેજ જોઈએ?"),
    ("kyc_help", "મારું KYC પેન્ડિંગ છે, શું કરવું?"),
    ("kyc_help", "KYC વેરિફિકેશન કેવી રીતે થાય છે?"),
    ("kyc_help", "શું મારું KYC પૂરું થયું છે?"),
    ("kyc_help", "મારે મારા KYC દસ્તાવેજ સબમિટ કરવા છે"),
    ("kyc_help", "મારું KYC કેમ રિજેક્ટ થયું?"),
    ("kyc_help", "KYC વેરિફિકેશનમાં કેટલો સમય લાગે છે?"),
    ("kyc_help", "શું હું વિડિયો કોલથી KYC કરી શકું?"),
    ("kyc_help", "મારે ફરીથી KYC કરવું છે"),
    ("kyc_help", "ઓનલાઈન KYC કેવી રીતે કરવું?"),
    ("kyc_help", "KYC ન હોવાથી મારું એકાઉન્ટ બંધ થયું"),
    ("kyc_help", "મારું એકાઉન્ટ KYCના કારણે હોલ્ડ પર છે"),
    ("kyc_help", "KYC પૂરું કરવાના પગલાં જણાવો"),
    ("kyc_help", "KYC અપડેટ કરવું છે"),

    # --- complaint (en) ---
    ("complaint", "I have a complaint"),
    ("complaint", "Money debited but not received"),
    ("complaint", "I want to file a complaint against this bank"),
    ("complaint", "My transaction failed but amount was deducted"),
    ("complaint", "I want to report a fraud transaction"),
    ("complaint", "This is a complaint about poor service"),
    ("complaint", "My complaint has not been resolved yet"),
    ("complaint", "I was charged twice for the same transaction"),
    ("complaint", "How do I lodge a complaint?"),
    ("complaint", "I need to escalate my complaint"),
    ("complaint", "My card was blocked without any reason"),
    ("complaint", "I want to complain about hidden charges"),
    ("complaint", "Someone made an unauthorized transaction on my account"),
    ("complaint", "My ATM did not dispense cash but money was deducted"),
    ("complaint", "I am not happy with the service, want to complain"),
    ("complaint", "Where can I register a complaint?"),
    # --- complaint (hi) ---
    ("complaint", "मुझे शिकायत करनी है"),
    ("complaint", "पैसे कट गए लेकिन मिले नहीं"),
    ("complaint", "मेरा ट्रांजैक्शन फेल हो गया लेकिन पैसे कट गए"),
    ("complaint", "मुझे फ्रॉड ट्रांजैक्शन की शिकायत करनी है"),
    ("complaint", "मेरी शिकायत अभी तक हल नहीं हुई"),
    ("complaint", "मुझसे दो बार पैसे काट लिए गए"),
    ("complaint", "शिकायत कैसे दर्ज करें?"),
    ("complaint", "मुझे अपनी शिकायत आगे बढ़ानी है"),
    ("complaint", "बिना कारण मेरा कार्ड ब्लॉक हो गया"),
    ("complaint", "मुझे छिपे हुए चार्जेस की शिकायत करनी है"),
    ("complaint", "मेरे खाते से बिना अनुमति पैसे निकाले गए"),
    ("complaint", "ATM से पैसे नहीं निकले लेकिन बैलेंस कट गया"),
    ("complaint", "सर्विस से खुश नहीं हूं, शिकायत करनी है"),
    ("complaint", "complaint kaise register kare"),
    ("complaint", "mere paise kat gaye lekin transaction fail dikha raha hai"),
    ("complaint", "शिकायत दर्ज करने का तरीका बताइए"),
    # --- complaint (gu) ---
    ("complaint", "મારે ફરિયાદ કરવી છે"),
    ("complaint", "પૈસા કપાયા પણ મળ્યા નહીં"),
    ("complaint", "મારું ટ્રાન્ઝેક્શન નિષ્ફળ ગયું પણ પૈસા કપાયા"),
    ("complaint", "મારે ફ્રોડ ટ્રાન્ઝેક્શનની ફરિયાદ કરવી છે"),
    ("complaint", "મારી ફરિયાદ હજુ સુધી ઉકેલાઈ નથી"),
    ("complaint", "મારી પાસેથી બે વાર પૈસા કપાયા"),
    ("complaint", "ફરિયાદ કેવી રીતે નોંધાવવી?"),
    ("complaint", "મારે મારી ફરિયાદ આગળ વધારવી છે"),
    ("complaint", "કોઈ કારણ વગર મારું કાર્ડ બ્લોક થયું"),
    ("complaint", "મારે છુપા ચાર્જીસની ફરિયાદ કરવી છે"),
    ("complaint", "મારા ખાતામાંથી પરવાનગી વગર પૈસા ઉપડ્યા"),
    ("complaint", "ATMમાંથી પૈસા ન નીકળ્યા પણ બેલેન્સ કપાયું"),
    ("complaint", "સર્વિસથી ખુશ નથી, ફરિયાદ કરવી છે"),
    ("complaint", "ફરિયાદ નોંધાવવાની રીત જણાવો"),
    ("complaint", "મારે આ બેંક વિરુદ્ધ ફરિયાદ કરવી છે"),
    ("complaint", "મારું કાર્ડ કેમ બ્લોક થયું, ફરિયાદ કરવી છે"),

    # --- greeting (en) ---
    ("greeting", "hi"),
    ("greeting", "hello"),
    ("greeting", "hello Saarthi"),
    ("greeting", "good morning"),
    ("greeting", "hey there"),
    ("greeting", "hi, how are you?"),
    ("greeting", "good evening"),
    ("greeting", "hey Saarthi, are you there?"),
    ("greeting", "hello, is anyone there?"),
    ("greeting", "hi there"),
    ("greeting", "good afternoon"),
    ("greeting", "greetings"),
    ("greeting", "hey"),
    ("greeting", "hello, I need some help"),
    ("greeting", "hi Saarthi"),
    ("greeting", "yo, is this the bank chatbot?"),
    # --- greeting (hi) ---
    ("greeting", "नमस्ते"),
    ("greeting", "नमस्कार"),
    ("greeting", "हैलो"),
    ("greeting", "क्या हाल है?"),
    ("greeting", "गुड मॉर्निंग"),
    ("greeting", "हाय सारथी"),
    ("greeting", "आप कैसे हैं?"),
    ("greeting", "नमस्ते सारथी"),
    ("greeting", "hi, kaise ho"),
    ("greeting", "नमस्ते जी"),
    ("greeting", "शुभ प्रभात"),
    ("greeting", "हेलो, कोई है क्या?"),
    ("greeting", "हाय, क्या हाल चाल?"),
    ("greeting", "गुड ईवनिंग"),
    ("greeting", "प्रणाम"),
    ("greeting", "हेलो, सारथी हो क्या तुम?"),
    # --- greeting (gu) ---
    ("greeting", "કેમ છો"),
    ("greeting", "નમસ્તે"),
    ("greeting", "હેલો"),
    ("greeting", "કેમ છો સારથી"),
    ("greeting", "શુભ સવાર"),
    ("greeting", "તમે કેમ છો?"),
    ("greeting", "હાય સારથી"),
    ("greeting", "કેમ છે તમારે?"),
    ("greeting", "નમસ્કાર"),
    ("greeting", "શુભ સાંજ"),
    ("greeting", "હેલો, કોઈ છે?"),
    ("greeting", "કેમ છો, મજામાં?"),
    ("greeting", "જય શ્રી કૃષ્ણ"),
    ("greeting", "હાય, શું ચાલે છે?"),
    ("greeting", "હેલો સારથી, તમે ત્યાં છો?"),
    ("greeting", "કેમ છો ભાઈ"),

    # --- general (en) ---
    ("general", "Tell me about savings accounts"),
    ("general", "What is FOIR?"),
    ("general", "What are the bank's working hours?"),
    ("general", "Tell me about fixed deposits"),
    ("general", "What is the interest rate on savings account?"),
    ("general", "How do I open a new account?"),
    ("general", "What is a credit score?"),
    ("general", "Tell me about your services"),
    ("general", "What is the minimum balance required?"),
    ("general", "How do I contact customer care?"),
    ("general", "What is net banking?"),
    ("general", "Tell me about mutual funds"),
    ("general", "What is CIBIL score?"),
    ("general", "How do I get a new debit card?"),
    ("general", "What is the difference between savings and current account?"),
    ("general", "Give me information about this bank"),
    # --- general (hi) ---
    ("general", "बैंक की जानकारी दो"),
    ("general", "FOIR क्या है?"),
    ("general", "सेविंग अकाउंट के बारे में बताओ"),
    ("general", "फिक्स्ड डिपॉजिट क्या होता है?"),
    ("general", "बैंक का समय क्या है?"),
    ("general", "नया अकाउंट कैसे खोलें?"),
    ("general", "क्रेडिट स्कोर क्या होता है?"),
    ("general", "आपकी सेवाओं के बारे में बताओ"),
    ("general", "मिनिमम बैलेंस कितना रखना होता है?"),
    ("general", "कस्टमर केयर से कैसे बात करें?"),
    ("general", "नेट बैंकिंग क्या है?"),
    ("general", "म्यूचुअल फंड के बारे में बताओ"),
    ("general", "CIBIL स्कोर क्या होता है?"),
    ("general", "नया डेबिट कार्ड कैसे मिलेगा?"),
    ("general", "सेविंग और करंट अकाउंट में क्या फर्क है?"),
    ("general", "इस बैंक के बारे में जानकारी दो"),
    # --- general (gu) ---
    ("general", "banking વિશે માહિતી આપો"),
    ("general", "FOIR શું છે?"),
    ("general", "સેવિંગ એકાઉન્ટ વિશે જણાવો"),
    ("general", "ફિક્સ્ડ ડિપોઝિટ શું છે?"),
    ("general", "બેંકનો સમય શું છે?"),
    ("general", "નવું એકાઉન્ટ કેવી રીતે ખોલવું?"),
    ("general", "ક્રેડિટ સ્કોર શું છે?"),
    ("general", "તમારી સેવાઓ વિશે જણાવો"),
    ("general", "મિનિમમ બેલેન્સ કેટલું રાખવું પડે?"),
    ("general", "કસ્ટમર કેર સાથે કેવી રીતે વાત કરવી?"),
    ("general", "નેટ બેન્કિંગ શું છે?"),
    ("general", "મ્યુચ્યુઅલ ફંડ વિશે જણાવો"),
    ("general", "CIBIL સ્કોર શું છે?"),
    ("general", "નવું ડેબિટ કાર્ડ કેવી રીતે મળે?"),
    ("general", "સેવિંગ અને કરંટ એકાઉન્ટમાં શું ફરક છે?"),
    ("general", "આ બેંક વિશે માહિતી આપો"),
]


@functools.lru_cache(maxsize=1)
def _model():
    from sentence_transformers import SentenceTransformer
    return SentenceTransformer("paraphrase-multilingual-MiniLM-L12-v2")


@functools.lru_cache(maxsize=1)
def _seed_embeddings():
    texts = [s[1] for s in SEEDS]
    return _model().encode(texts, convert_to_numpy=True, normalize_embeddings=True)


def classify(text: str) -> tuple[str, float]:
    q = _model().encode([text], convert_to_numpy=True, normalize_embeddings=True)[0]
    sims = _seed_embeddings() @ q
    best = int(sims.argmax())
    score = float(sims[best])
    if score < THRESHOLD:
        return "general", score
    return SEEDS[best][0], score


if __name__ == "__main__":
    # ponytail self-check: structural check needs no deps; live check needs
    # `pip install sentence-transformers` (not run here, run it yourself).
    from collections import Counter

    counts = Counter(intent for intent, _ in SEEDS)
    assert set(counts) == set(INTENTS), f"missing seeds for {set(INTENTS) - set(counts)}"
    print(f"{len(SEEDS)} seeds:", dict(counts))
    print(classify("मुझे लोन चाहिए"))
    print(classify("xyzzy plugh qwerty"))
